name: Build and deploy ASP.Net Core app to Azure Web App - ideasandinvestors

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CONFIGURATION: Release
  WORKING_DIRECTORY: './IdeasAndInvestors'  # Update this path to the correct solution or project directory
  DOTNET_ROOT: 'C:\Program Files\dotnet' # It's usually not necessary to define this unless specifically required

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}/IdeasAndInvestors.sln

      - name: Build with dotnet
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: dotnet publish
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB4F739727014072BD3242DF12FAA428 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B2A70A23902549F18299015703664EC1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA8422518842480783E2B15FF111578B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ideasandinvestors'
          slot-name: 'Production'
          package: ${{ github.workspace }}/myapp
